<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PromiseA+</title>
</head>
<body>
    <script>

        // 是否有 iterator 接口
        const hasIterator = (data) => {
            return data !== null && typeof data[Symbol.iterator] === 'function';
        }

        // 无 iterator 接口异常
        const noIteratorError = (data) => {
            return new TypeError(typeof data + `${data === null ? ' null' : ''} is not iterable (cannot read property Symbol(Symbol.iterator))`)

        }
        function resolvePromise(promise, x, resolve, reject) {
            if (promise === x) { // 如果相等了，说明return的是自己，抛出类型错误并返回
                return reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
            }
            if ( ['object', 'function'].includes(typeof x) ) {
                if (x === null) { // x 为 null 直接返回，走后面的逻辑会报错
                    return resolve(x);
                }
                let then;
                try {
                    then = x.then;
                } catch(error) { // 如果取 x.then 的值时抛出错误 error ，则以 error 为据因拒绝 promise
                    return reject(error);
                }
                
                if (typeof then === 'function') { // 如果 then 是函数
                    let called = false;
                    try {
                        then.call( // this 指向 x
                        x, y => { // 如果 resolvePromise 以值 y 为参数被调用，则运行 [[Resolve]](promise, y)
                            // 如果 resolvePromise 和 rejectPromise 均被调用，
                            // 或者被同一参数调用了多次，则优先采用首次调用并忽略剩下的调用
                            // 实现这条需要前面加一个变量 called
                            if (called) return;
                            called = true;
                            resolvePromise(promise, y, resolve, reject);
                        }, r => { // 如果 rejectPromise 以据因 r 为参数被调用，则以据因 r 拒绝 promise
                            if (called) return;
                            called = true;
                            reject(r);
                        });
                    } catch (error) { // 如果调用 then 方法抛出了异常 error：
                        // 如果 resolvePromise 或 rejectPromise 已经被调用，直接返回
                        if (called) return;

                        // 否则以 error 为据因拒绝 promise
                        reject(error);
                    }
                } else { // 如果 then 不是函数，以 x 为参数执行 promise
                    resolve(x);
                }
            } else { // 如果 x 不为对象或者函数，以 x 为参数执行 promise
                resolve(x);
            }
        }

        const PENDING = 'pending';
        const FULFILLED = 'fulfilled';
        const REJECTED = 'rejected';
        class MyPromise {
            constructor(excutor) {
                try {
                    excutor(this.resolve, this.reject);
                } catch(err) {
                    this.reject(err)
                }
                
            }
            status = PENDING;
            value = null;
            reason = null;
            resolveCallbackList = [];
            rejectCallbackList = [];

            static resolve (parameter) {
                if (parameter instanceof MyPromise) {
                    return parameter
                }
                return new MyPromise(resolve => {
                    resolve(parameter);
                })
            }
            
            static reject (parameter) {
                return new MyPromise((resolve, reject) => {
                    reject(parameter);
                })
            }

            // 更新成功状态
            resolve = (value) => {
                if (this.status === PENDING) {
                    this.status = FULFILLED;
                    this.value = value;
                }
                while(this.resolveCallbackList.length) {
                    this.resolveCallbackList.shift()(value);
                }
            }

            // 更新失败状态
            reject = (reason) => {
                if (this.status === PENDING) {
                    this.status = REJECTED;
                    this.reason = reason;
                }
                while(this.rejectCallbackList.length) {
                    this.rejectCallbackList.shift()(reason);
                }
            }

            // 异步调用
            then(onFulfilled, onRejected) {
                onFulfilled = typeof onFulfilled === 'function' && onFulfilled !== Function ? onFulfilled : value => value;
                onRejected = typeof onRejected === 'function' && onRejected !== Function ? onRejected : reason => {throw reason};

                const promise1 = new MyPromise((resolve, reject) => {
                    const commonMicrotask = (type = FULFILLED) => () => { // 接收一个区分参数，返回一个函数
                        // 创建一个微任务等待 promise2 完成初始化
                        queueMicrotask(() => {
                            try {
                                // 调用成功/失败回调，并且把值/原因返回
                                const x = type === FULFILLED ? onFulfilled(this.value) : onRejected(this.reason);
                                // 传入 resolvePromise 集中处理
                                resolvePromise(promise1, x, resolve, reject);
                            } catch (error) {
                                reject(error)
                            } 
                        })
                    }
                    
                    if(this.status === PENDING) {
                        this.resolveCallbackList.push(commonMicrotask(FULFILLED));
                        this.rejectCallbackList.push(commonMicrotask(REJECTED));
                    } else if(this.status === FULFILLED) {
                        commonMicrotask(FULFILLED)();
                    } else if (this.status === REJECTED) {
                        commonMicrotask(REJECTED)();
                    }
                })
                return promise1;
            }
            
            // 异常捕获
            catch (onRejected) {
                return this.then(null, onRejected);
            }

            // 始终执行 finally
            finally(func) {
                return this.then(
                    value =>  MyPromise.resolve(func()).then(() => value),
                    err => MyPromise.resolve(func()).then(() => { throw err })
                );
            }

            // --------------- all ---------------
            static all(promiseList) {
                return new MyPromise((resolve, reject) => {
                    // 非null的对象 并且有 iterator 借口
                    if(hasIterator(promiseList)) {
                        const len = promiseList.length;
                        let count = 0
                        if (len === 0) resolve([]);
                        const result = [];

                        // 方法一
                        // promiseList.forEach((promise, index) => {
                        //     MyPromise.resolve(promise).then(value => {
                        //         count++;
                        //         result[index] = value;
                        //         if(count === len) {
                        //             resolve(result);
                        //         }
                        //     }, reason => {
                        //         reject(reason);
                        //     });
                        // });

                        // 方法二
                        for (let i = 0; i < len; i ++) {
                            if (promiseList[i] instanceof MyPromise) { // promise
                                promiseList[i].then(value => {
                                    result[i] = value;
                                    ++ count;
                                }, reject);
                            } else {
                                ++ count;
                                result[i] = promiseList[i];
                            }
                        }
                        queueMicrotask(() => { // then 是微任务，添加一个新的微任务等then的执行结果
                            count === len && resolve(result);
                        })
                    } else {
                        reject( noIteratorError(promiseList) )
                    }
                })
            }

            // --------------- race ---------------
            static race (promiseList) {
                return new MyPromise((resolve, reject) => {
                    if(hasIterator(promiseList)) {
                        for(let i = 0; i < promiseList.length; i++){
                            MyPromise.resolve(promiseList[i]).then(value => {
                                resolve(value);
                            }, reason => {
                                reject(reason);     
                            });
                        }  
                    } else {
                        reject( noIteratorError(promiseList) )
                    }
                })
            }

            // --------------- any ---------------
            static any (promiseList) {
                return new MyPromise((resolve, reject) => {
                    const result = [];
                    let count = 0;
                    const length = promiseList.length;
                    if(hasIterator(promiseList)) {
                        for(let i = 0; i < length; i++){
                            MyPromise.resolve(promiseList[i]).then(value => {
                                resolve(value);
                            }, reason => {
                                result[i] = reason;
                                ++ count;
                                if(count === length) reject(result)
                            });
                        }  
                    } else {
                        reject( noIteratorError(promiseList) )
                    }
                })
            }

            // --------------- allSettled ---------------
            static allSettled(promiseList) {
                return new MyPromise((resolve, reject) => {
                    if(hasIterator(promiseList)) {
                        const len = promiseList.length;
                        if( len === 0 ) return [];
                        const result = [];
                        for(let i = 0; i < len; i ++) {
                            if(promiseList[i] instanceof MyPromise) {
                                promiseList[i].then(value => {
                                    result[i] = {status: 'fulfilled', value}
                                }, reason => {
                                    result[i] = {status: 'rejected', reason}
                                })
                            } else {
                                result[i] = {status: 'fulfilled', value: promiseList[i]};
                            }
                        }
                        queueMicrotask(() => { // then 是微任务，添加一个新的微任务等then的执行结果
                            resolve(result)
                        })
                    } else {
                        reject( noIteratorError(promiseList) )
                    }
                })
            }
        }

        // --------------- defered ---------------
        MyPromise.deferred = function () {
            const dfd = {};
            dfd.promise = new MyPromise( (resolve, reject) => {
                dfd.resolve = resolve;
                dfd.reject = reject;
            })
            return dfd;
        }

        // --------------- test ---------------
        const resolved = MyPromise.resolve(42);
        const rejected = MyPromise.reject(-1);
        const alsoRejected = MyPromise.reject(Infinity);

        MyPromise.any([resolved, rejected, alsoRejected]).then(function (result) {
            console.log(result); // 42
        });

        MyPromise.race([1,rejected, alsoRejected]).then(function (result) {
            console.log('race', result);
        }).catch(function (results) {
            console.log('catch', results); // [-1, Infinity]
        });

        // MyPromise.resolve().then(() => {
        //     console.log(0);
        //     return MyPromise.reject(4);
        // }).then((res) => {
        //     console.log(res)
        // }).catch((err)=> {
        //     console.log('ssss', err);
        // }).finally(() => {
        //     console.log('ssssaaa');
        // })

        // const all = MyPromise.all([newp,2,3]);
        // all.then(value => {
        //     console.log('all', value);
        // })
        // all.catch(err => {
        //     console.log('err', err);
        // })


    </script>
</body>
</html>